import { Stack } from "./stack";

export const initialState = [
  new Stack(["white", "white", "white", "white", "white"]),
  new Stack([]),
  new Stack([]),
  new Stack([]),
  new Stack(["black", "black", "black"]),
  new Stack([]),
  new Stack(["black", "black", "black", "black", "black"]),
  new Stack([]),
  new Stack([]),
  new Stack([]),
  new Stack([]),
  new Stack(["white", "white"]),
  new Stack(["black", "black", "black", "black", "black"]),
  new Stack([]),
  new Stack([]),
  new Stack([]),
  new Stack(["white", "white", "white"]),
  new Stack([]),
  new Stack(["white", "white", "white", "white", "white"]),
  new Stack([]),
  new Stack([]),
  new Stack([]),
  new Stack([]),
  new Stack(["black", "black"]),
];
